# Generated by CMake, DO NOT EDIT
/Users/Marijn/Projects/OpenRCT2/Main/libs-ios/libpng/CMakeFiles/cmake.check_cache: \
/Users/Marijn/Projects/OpenRCT2/Main/libs-ios/libpng/CMakeFiles/3.5.2/CMakeCCompiler.cmake\
/Users/Marijn/Projects/OpenRCT2/Main/libs-ios/libpng/CMakeFiles/3.5.2/CMakeSystem.cmake\
/Users/Marijn/Projects/OpenRCT2/Main/libs-ios/libpng/CMakeLists.txt\
/Users/Marijn/Projects/OpenRCT2/Main/libs-ios/libpng/libpng-config.in\
/Users/Marijn/Projects/OpenRCT2/Main/libs-ios/libpng/libpng.pc.in\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeCInformation.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeCommonLanguageInclude.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeGenericSystem.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeLanguageInformation.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeParseArguments.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeSystemSpecificInformation.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Compiler/AppleClang-C.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Compiler/Clang.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Compiler/GNU.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPackageMessage.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindZLIB.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Platform/Darwin-AppleClang-C.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Platform/Darwin-Clang-C.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Platform/Darwin-Clang.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Platform/Darwin-Initialize.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Platform/Darwin.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Platform/UnixPaths.cmake\
/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/SelectLibraryConfigurations.cmake
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H/Users/Marijn/Projects/OpenRCT2/Main/libs-ios/libpng -B/Users/Marijn/Projects/OpenRCT2/Main/libs-ios/libpng
